# Generated by Django 2.2.6 on 2019-11-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='image',
            field=models.ImageField(default=1234, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(default='12345', max_length=100),
        ),
    ]
